#! /bin/bash

sudo rmmod pcspkr

xmodmap -e "clear lock" #disable caps lock switch
xmodmap -e "keysym Caps_Lock = Escape" #set caps_lock as escape

xset s off &
xset -dpms &

export SUDO_ASKPASS=/usr/AamonDwmScripts/sudo_dmenu
