-- -- require("aamon.statusline")
require("aamon.sets")
require("aamon.keybindings")
require("aamon.autocmds")

require("plugins.packer")
require("plugins.lualine")
require("plugins.lsp")
require("plugins.undotree")
require("plugins.treesitter")
require("plugins.telescope")
require("plugins.harpoon")
require("plugins.comment")
require("plugins.autoclose")
require("plugins.which-key")
